/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      // 2026-05-18：對齊 src/styles/tokens.css 的 CSS variables。
      // 改 hex 一律改 tokens.css 不改這裡；這裡只是把 token 名稱對應到
      // Tailwind utility class（如 `bg-brand` / `text-ink-soft`）。
      colors: {
        brand: 'var(--brand)',
        'brand-dark': 'var(--brand-dark)',
        'brand-dark-hover': 'var(--brand-dark-hover)',
        'brand-darker': 'var(--brand-darker)',
        'brand-light': 'var(--brand-light)',
        'brand-light-deep': 'var(--brand-light-deep)',
        'brand-soft': 'var(--brand-soft)',
        'brand-light-soft': 'var(--brand-light-soft)',
        internal: 'var(--internal)',
        'internal-soft': 'var(--internal-soft)',
        external: 'var(--external)',
        'external-soft': 'var(--external-soft)',
        accent: 'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        highlight: 'var(--highlight)',
        star: 'var(--star)',
        info: 'var(--info)',
        'info-soft': 'var(--info-soft)',
        'info-ink': 'var(--info-ink)',
        warning: 'var(--warning)',
        'warning-soft': 'var(--warning-soft)',
        'warning-ink': 'var(--warning-ink)',
        danger: 'var(--danger)',
        'danger-soft': 'var(--danger-soft)',
        'danger-ink': 'var(--danger-ink)',
        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        'success-ink': 'var(--success-ink)',
        inclusive: 'var(--inclusive)',
        'inclusive-soft': 'var(--inclusive-soft)',
        subflow: 'var(--subflow)',
        'subflow-soft': 'var(--subflow-soft)',
        'external-node': 'var(--external-node)',
        'external-node-soft': 'var(--external-node-soft)',
        paper: 'var(--paper)',
        'paper-2': 'var(--paper-2)',
        card: 'var(--card)',
        ink: 'var(--ink)',
        'ink-soft': 'var(--ink-soft)',
        'ink-faint': 'var(--ink-faint)',
        line: 'var(--line)',
        'line-dim': 'var(--line-dim)',
      },
    },
  },
  plugins: [],
}
